/*
 * game_state.h - reads what the game is doing straight out of emulated RAM,
 * so host code (touch controls, cheats, debug info) never has to guess.
 *
 * The game keeps its globals at fixed offsets from A6; the names and
 * meanings below come from fe2/fe2_modded.s (the A6_* equates and the code that
 * uses them).
 */
#ifndef GAME_STATE_H
#define GAME_STATE_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C"
{
#endif

/* FE2_USE_MODDED comes from CMake (GLF_MODDED_FE2): 1 for the modded game
 * code (fe2/fe2_modded.s), 0 for the original (fe2/fe2.s). Host code for a
 * mod goes inside #if FE2_USE_MODDED, as its labels only exist there. */
#ifndef FE2_USE_MODDED
#define FE2_USE_MODDED 1
#endif

/* generated by tools/build_fe2.py */
#if FE2_USE_MODDED
#include "fe2_labels.h"
#else
#include "fe2_orig_labels.h"
#endif

/* L5eb6_a6_base: where A6 points */
#define GAME_A6 FE2_a6_base

/* A6 offsets */
#define A6_SCREEN_OWNER 6     /* word: module that owns the main screen */
#define A6_PLAYER_SHIP  674   /* long: the player's ship object */
#define A6_FLIGHT_STATE 704   /* byte: see FlightStatus */
#define A6_FLIGHT_FLAGS 705   /* byte: bit 0 engines off */
#define A6_3DVIEW_MODE  706   /* byte: A6_plr_3dview_mode, see FlightView */
#define A6_GAME_DATA    14470 /* long: A6_game_data, ship models etc */
#define A6_OPT_ELITE_CONTROLS 10445 /* byte: $ff steering x rolls, 0 it yaws */

/* Values of A6_SCREEN_OWNER: the owning module's offset in the module
 * table (set with 66(a5) - L45318) */
enum
{
	OWNER_NONE = 0,
	OWNER_GALAXY_MAP = 16,   /* L820ee_mod_starsystemsview */
	OWNER_FLIGHT = 24,       /* L61468_mod_player */
	OWNER_SYSTEM_MAP = 40,   /* L4b1ca, mod5 SystemView */
	OWNER_OPTIONS = 80,      /* L7213a, mod10 options / load / save */
	OWNER_STATION = 96,      /* L75b64_mod_station_services */
	OWNER_SHIP_SCREEN = 112, /* L7ded6_mod_shipscreen */
};

typedef enum
{
	SCREEN_TITLE,      /* intro, or no game running */
	SCREEN_FLIGHT,     /* 3D view from (or of) the player's ship */
	SCREEN_GALAXY_MAP, /* sector / galaxy map */
	SCREEN_SYSTEM_MAP, /* orrery of the current system */
	SCREEN_OPTIONS,    /* game options, load and save */
	SCREEN_STATION,    /* station / starport services */
	SCREEN_SHIP,       /* ship information and shipyard */
	SCREEN_OTHER,
	SCREEN_COUNT
} GameScreen;

/* A6_plr_3dview_mode, cycled by F1 (L63e30) */
typedef enum
{
	VIEW_FRONT,
	VIEW_REAR,
	VIEW_TOP_TURRET,
	VIEW_BOTTOM_TURRET,
	VIEW_EXTERNAL,
	VIEW_COUNT
} FlightView;

/* A6+704, the status line drawn by the panel (L6f18e) */
typedef enum
{
	FLIGHT_MANUAL,
	FLIGHT_AUTOPILOT,    /* $04 */
	FLIGHT_TAKE_OFF,     /* $48 */
	FLIGHT_DOCKED,       /* $54 */
	FLIGHT_LANDED,       /* $60 */
	FLIGHT_LANDED_ROUGH, /* $68 */
	FLIGHT_COUNT
} FlightStatus;

GameScreen game_screen(void);
int game_screen_owner(void); /* raw A6_SCREEN_OWNER, for debugging */
FlightView game_flight_view(void);
FlightStatus game_flight_status(void);
bool game_engines_off(void);
/* The player's ship object, 0 when there is none yet */
unsigned int game_player_ship(void);

const char *game_screen_name(GameScreen s);
const char *game_view_name(FlightView v);
const char *game_status_name(FlightStatus s);

/* Lbuildtag_marker: a short plain-ASCII word at the end of fe2_modded.s,
 * changed whenever that file changes. Shown on the DEBUG page so a rebuild
 * that didn't actually pick up the latest fe2_modded.s is obvious at a
 * glance (the word on screen won't match what's now in the source).
 * "ORIGINAL" in the unmodded build, which has no such slot. */
const char *game_build_tag(void);

#ifdef __cplusplus
}
#endif

#endif /* GAME_STATE_H */
